/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemHealthRouteImport } from './routes/system-health'
import { Route as SettingsWebhooksRouteImport } from './routes/settings-webhooks'
import { Route as SettingsTokenUsageRouteImport } from './routes/settings-token-usage'
import { Route as SettingsTeamRouteImport } from './routes/settings-team'
import { Route as SettingsSsoRouteImport } from './routes/settings-sso'
import { Route as SettingsSecurityRouteImport } from './routes/settings-security'
import { Route as SettingsRulesLibraryRouteImport } from './routes/settings-rules-library'
import { Route as SettingsProvidersRouteImport } from './routes/settings-providers'
import { Route as SettingsProviderDegradationRouteImport } from './routes/settings-provider-degradation'
import { Route as SettingsPrivacyRedactionRouteImport } from './routes/settings-privacy-redaction'
import { Route as SettingsOrganizationRouteImport } from './routes/settings-organization'
import { Route as SettingsOperationsRouteImport } from './routes/settings-operations'
import { Route as SettingsNotificationsRouteImport } from './routes/settings-notifications'
import { Route as SettingsLlmProvidersRouteImport } from './routes/settings-llm-providers'
import { Route as SettingsJobsRouteImport } from './routes/settings-jobs'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings-integrations'
import { Route as SettingsGitProvidersRouteImport } from './routes/settings-git-providers'
import { Route as SettingsGeneralRouteImport } from './routes/settings-general'
import { Route as SettingsContractValidationRouteImport } from './routes/settings-contract-validation'
import { Route as SettingsConcurrencyRouteImport } from './routes/settings-concurrency'
import { Route as SettingsCodeReviewRouteImport } from './routes/settings-code-review'
import { Route as SettingsByokRouteImport } from './routes/settings-byok'
import { Route as SettingsBillingRouteImport } from './routes/settings-billing'
import { Route as SettingsAuditLogsRouteImport } from './routes/settings-audit-logs'
import { Route as SettingsAppearanceRouteImport } from './routes/settings-appearance'
import { Route as SettingsAdoptionAnalyticsRouteImport } from './routes/settings-adoption-analytics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionRecoveryRouteImport } from './routes/session-recovery'
import { Route as ScanProgressRouteImport } from './routes/scan-progress'
import { Route as ScanErrorRecoveryRouteImport } from './routes/scan-error-recovery'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as HelpDiagnosticsRouteImport } from './routes/help-diagnostics'
import { Route as AdoptionAnalyticsRouteImport } from './routes/adoption-analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as ReviewsReviewIdRouteImport } from './routes/reviews.$reviewId'
import { Route as RepositoriesRepositoryIdRouteImport } from './routes/repositories.$repositoryId'
import { Route as ReportsViewerRouteImport } from './routes/reports.viewer'
import { Route as ReportsGenerateRouteImport } from './routes/reports.generate'
import { Route as DashboardCodeCityRouteImport } from './routes/dashboard.code-city'

const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebhooksRoute = SettingsWebhooksRouteImport.update({
  id: '/settings-webhooks',
  path: '/settings-webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTokenUsageRoute = SettingsTokenUsageRouteImport.update({
  id: '/settings-token-usage',
  path: '/settings-token-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings-team',
  path: '/settings-team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSsoRoute = SettingsSsoRouteImport.update({
  id: '/settings-sso',
  path: '/settings-sso',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings-security',
  path: '/settings-security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesLibraryRoute = SettingsRulesLibraryRouteImport.update({
  id: '/settings-rules-library',
  path: '/settings-rules-library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/settings-providers',
  path: '/settings-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProviderDegradationRoute =
  SettingsProviderDegradationRouteImport.update({
    id: '/settings-provider-degradation',
    path: '/settings-provider-degradation',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsPrivacyRedactionRoute =
  SettingsPrivacyRedactionRouteImport.update({
    id: '/settings-privacy-redaction',
    path: '/settings-privacy-redaction',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/settings-organization',
  path: '/settings-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOperationsRoute = SettingsOperationsRouteImport.update({
  id: '/settings-operations',
  path: '/settings-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings-notifications',
  path: '/settings-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLlmProvidersRoute = SettingsLlmProvidersRouteImport.update({
  id: '/settings-llm-providers',
  path: '/settings-llm-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsJobsRoute = SettingsJobsRouteImport.update({
  id: '/settings-jobs',
  path: '/settings-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings-integrations',
  path: '/settings-integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGitProvidersRoute = SettingsGitProvidersRouteImport.update({
  id: '/settings-git-providers',
  path: '/settings-git-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings-general',
  path: '/settings-general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsContractValidationRoute =
  SettingsContractValidationRouteImport.update({
    id: '/settings-contract-validation',
    path: '/settings-contract-validation',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsConcurrencyRoute = SettingsConcurrencyRouteImport.update({
  id: '/settings-concurrency',
  path: '/settings-concurrency',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCodeReviewRoute = SettingsCodeReviewRouteImport.update({
  id: '/settings-code-review',
  path: '/settings-code-review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsByokRoute = SettingsByokRouteImport.update({
  id: '/settings-byok',
  path: '/settings-byok',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings-billing',
  path: '/settings-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditLogsRoute = SettingsAuditLogsRouteImport.update({
  id: '/settings-audit-logs',
  path: '/settings-audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings-appearance',
  path: '/settings-appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAdoptionAnalyticsRoute =
  SettingsAdoptionAnalyticsRouteImport.update({
    id: '/settings-adoption-analytics',
    path: '/settings-adoption-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRecoveryRoute = SessionRecoveryRouteImport.update({
  id: '/session-recovery',
  path: '/session-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanProgressRoute = ScanProgressRouteImport.update({
  id: '/scan-progress',
  path: '/scan-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanErrorRecoveryRoute = ScanErrorRecoveryRouteImport.update({
  id: '/scan-error-recovery',
  path: '/scan-error-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDiagnosticsRoute = HelpDiagnosticsRouteImport.update({
  id: '/help-diagnostics',
  path: '/help-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptionAnalyticsRoute = AdoptionAnalyticsRouteImport.update({
  id: '/adoption-analytics',
  path: '/adoption-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewsRoute,
} as any)
const ReviewsReviewIdRoute = ReviewsReviewIdRouteImport.update({
  id: '/$reviewId',
  path: '/$reviewId',
  getParentRoute: () => ReviewsRoute,
} as any)
const RepositoriesRepositoryIdRoute =
  RepositoriesRepositoryIdRouteImport.update({
    id: '/$repositoryId',
    path: '/$repositoryId',
    getParentRoute: () => RepositoriesRoute,
  } as any)
const ReportsViewerRoute = ReportsViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsGenerateRoute = ReportsGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => ReportsRoute,
} as any)
const DashboardCodeCityRoute = DashboardCodeCityRouteImport.update({
  id: '/dashboard/code-city',
  path: '/dashboard/code-city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adoption-analytics': typeof AdoptionAnalyticsRoute
  '/help-diagnostics': typeof HelpDiagnosticsRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/my-work': typeof MyWorkRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/reviews': typeof ReviewsRouteWithChildren
  '/scan-error-recovery': typeof ScanErrorRecoveryRoute
  '/scan-progress': typeof ScanProgressRoute
  '/session-recovery': typeof SessionRecoveryRoute
  '/settings': typeof SettingsRoute
  '/settings-adoption-analytics': typeof SettingsAdoptionAnalyticsRoute
  '/settings-appearance': typeof SettingsAppearanceRoute
  '/settings-audit-logs': typeof SettingsAuditLogsRoute
  '/settings-billing': typeof SettingsBillingRoute
  '/settings-byok': typeof SettingsByokRoute
  '/settings-code-review': typeof SettingsCodeReviewRoute
  '/settings-concurrency': typeof SettingsConcurrencyRoute
  '/settings-contract-validation': typeof SettingsContractValidationRoute
  '/settings-general': typeof SettingsGeneralRoute
  '/settings-git-providers': typeof SettingsGitProvidersRoute
  '/settings-integrations': typeof SettingsIntegrationsRoute
  '/settings-jobs': typeof SettingsJobsRoute
  '/settings-llm-providers': typeof SettingsLlmProvidersRoute
  '/settings-notifications': typeof SettingsNotificationsRoute
  '/settings-operations': typeof SettingsOperationsRoute
  '/settings-organization': typeof SettingsOrganizationRoute
  '/settings-privacy-redaction': typeof SettingsPrivacyRedactionRoute
  '/settings-provider-degradation': typeof SettingsProviderDegradationRoute
  '/settings-providers': typeof SettingsProvidersRoute
  '/settings-rules-library': typeof SettingsRulesLibraryRoute
  '/settings-security': typeof SettingsSecurityRoute
  '/settings-sso': typeof SettingsSsoRoute
  '/settings-team': typeof SettingsTeamRoute
  '/settings-token-usage': typeof SettingsTokenUsageRoute
  '/settings-webhooks': typeof SettingsWebhooksRoute
  '/system-health': typeof SystemHealthRoute
  '/dashboard/code-city': typeof DashboardCodeCityRoute
  '/reports/generate': typeof ReportsGenerateRoute
  '/reports/viewer': typeof ReportsViewerRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adoption-analytics': typeof AdoptionAnalyticsRoute
  '/help-diagnostics': typeof HelpDiagnosticsRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/my-work': typeof MyWorkRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/scan-error-recovery': typeof ScanErrorRecoveryRoute
  '/scan-progress': typeof ScanProgressRoute
  '/session-recovery': typeof SessionRecoveryRoute
  '/settings': typeof SettingsRoute
  '/settings-adoption-analytics': typeof SettingsAdoptionAnalyticsRoute
  '/settings-appearance': typeof SettingsAppearanceRoute
  '/settings-audit-logs': typeof SettingsAuditLogsRoute
  '/settings-billing': typeof SettingsBillingRoute
  '/settings-byok': typeof SettingsByokRoute
  '/settings-code-review': typeof SettingsCodeReviewRoute
  '/settings-concurrency': typeof SettingsConcurrencyRoute
  '/settings-contract-validation': typeof SettingsContractValidationRoute
  '/settings-general': typeof SettingsGeneralRoute
  '/settings-git-providers': typeof SettingsGitProvidersRoute
  '/settings-integrations': typeof SettingsIntegrationsRoute
  '/settings-jobs': typeof SettingsJobsRoute
  '/settings-llm-providers': typeof SettingsLlmProvidersRoute
  '/settings-notifications': typeof SettingsNotificationsRoute
  '/settings-operations': typeof SettingsOperationsRoute
  '/settings-organization': typeof SettingsOrganizationRoute
  '/settings-privacy-redaction': typeof SettingsPrivacyRedactionRoute
  '/settings-provider-degradation': typeof SettingsProviderDegradationRoute
  '/settings-providers': typeof SettingsProvidersRoute
  '/settings-rules-library': typeof SettingsRulesLibraryRoute
  '/settings-security': typeof SettingsSecurityRoute
  '/settings-sso': typeof SettingsSsoRoute
  '/settings-team': typeof SettingsTeamRoute
  '/settings-token-usage': typeof SettingsTokenUsageRoute
  '/settings-webhooks': typeof SettingsWebhooksRoute
  '/system-health': typeof SystemHealthRoute
  '/dashboard/code-city': typeof DashboardCodeCityRoute
  '/reports/generate': typeof ReportsGenerateRoute
  '/reports/viewer': typeof ReportsViewerRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews': typeof ReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adoption-analytics': typeof AdoptionAnalyticsRoute
  '/help-diagnostics': typeof HelpDiagnosticsRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/my-work': typeof MyWorkRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/reviews': typeof ReviewsRouteWithChildren
  '/scan-error-recovery': typeof ScanErrorRecoveryRoute
  '/scan-progress': typeof ScanProgressRoute
  '/session-recovery': typeof SessionRecoveryRoute
  '/settings': typeof SettingsRoute
  '/settings-adoption-analytics': typeof SettingsAdoptionAnalyticsRoute
  '/settings-appearance': typeof SettingsAppearanceRoute
  '/settings-audit-logs': typeof SettingsAuditLogsRoute
  '/settings-billing': typeof SettingsBillingRoute
  '/settings-byok': typeof SettingsByokRoute
  '/settings-code-review': typeof SettingsCodeReviewRoute
  '/settings-concurrency': typeof SettingsConcurrencyRoute
  '/settings-contract-validation': typeof SettingsContractValidationRoute
  '/settings-general': typeof SettingsGeneralRoute
  '/settings-git-providers': typeof SettingsGitProvidersRoute
  '/settings-integrations': typeof SettingsIntegrationsRoute
  '/settings-jobs': typeof SettingsJobsRoute
  '/settings-llm-providers': typeof SettingsLlmProvidersRoute
  '/settings-notifications': typeof SettingsNotificationsRoute
  '/settings-operations': typeof SettingsOperationsRoute
  '/settings-organization': typeof SettingsOrganizationRoute
  '/settings-privacy-redaction': typeof SettingsPrivacyRedactionRoute
  '/settings-provider-degradation': typeof SettingsProviderDegradationRoute
  '/settings-providers': typeof SettingsProvidersRoute
  '/settings-rules-library': typeof SettingsRulesLibraryRoute
  '/settings-security': typeof SettingsSecurityRoute
  '/settings-sso': typeof SettingsSsoRoute
  '/settings-team': typeof SettingsTeamRoute
  '/settings-token-usage': typeof SettingsTokenUsageRoute
  '/settings-webhooks': typeof SettingsWebhooksRoute
  '/system-health': typeof SystemHealthRoute
  '/dashboard/code-city': typeof DashboardCodeCityRoute
  '/reports/generate': typeof ReportsGenerateRoute
  '/reports/viewer': typeof ReportsViewerRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adoption-analytics'
    | '/help-diagnostics'
    | '/issues'
    | '/login'
    | '/my-work'
    | '/onboarding'
    | '/reports'
    | '/repositories'
    | '/reviews'
    | '/scan-error-recovery'
    | '/scan-progress'
    | '/session-recovery'
    | '/settings'
    | '/settings-adoption-analytics'
    | '/settings-appearance'
    | '/settings-audit-logs'
    | '/settings-billing'
    | '/settings-byok'
    | '/settings-code-review'
    | '/settings-concurrency'
    | '/settings-contract-validation'
    | '/settings-general'
    | '/settings-git-providers'
    | '/settings-integrations'
    | '/settings-jobs'
    | '/settings-llm-providers'
    | '/settings-notifications'
    | '/settings-operations'
    | '/settings-organization'
    | '/settings-privacy-redaction'
    | '/settings-provider-degradation'
    | '/settings-providers'
    | '/settings-rules-library'
    | '/settings-security'
    | '/settings-sso'
    | '/settings-team'
    | '/settings-token-usage'
    | '/settings-webhooks'
    | '/system-health'
    | '/dashboard/code-city'
    | '/reports/generate'
    | '/reports/viewer'
    | '/repositories/$repositoryId'
    | '/reviews/$reviewId'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adoption-analytics'
    | '/help-diagnostics'
    | '/issues'
    | '/login'
    | '/my-work'
    | '/onboarding'
    | '/reports'
    | '/repositories'
    | '/scan-error-recovery'
    | '/scan-progress'
    | '/session-recovery'
    | '/settings'
    | '/settings-adoption-analytics'
    | '/settings-appearance'
    | '/settings-audit-logs'
    | '/settings-billing'
    | '/settings-byok'
    | '/settings-code-review'
    | '/settings-concurrency'
    | '/settings-contract-validation'
    | '/settings-general'
    | '/settings-git-providers'
    | '/settings-integrations'
    | '/settings-jobs'
    | '/settings-llm-providers'
    | '/settings-notifications'
    | '/settings-operations'
    | '/settings-organization'
    | '/settings-privacy-redaction'
    | '/settings-provider-degradation'
    | '/settings-providers'
    | '/settings-rules-library'
    | '/settings-security'
    | '/settings-sso'
    | '/settings-team'
    | '/settings-token-usage'
    | '/settings-webhooks'
    | '/system-health'
    | '/dashboard/code-city'
    | '/reports/generate'
    | '/reports/viewer'
    | '/repositories/$repositoryId'
    | '/reviews/$reviewId'
    | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/adoption-analytics'
    | '/help-diagnostics'
    | '/issues'
    | '/login'
    | '/my-work'
    | '/onboarding'
    | '/reports'
    | '/repositories'
    | '/reviews'
    | '/scan-error-recovery'
    | '/scan-progress'
    | '/session-recovery'
    | '/settings'
    | '/settings-adoption-analytics'
    | '/settings-appearance'
    | '/settings-audit-logs'
    | '/settings-billing'
    | '/settings-byok'
    | '/settings-code-review'
    | '/settings-concurrency'
    | '/settings-contract-validation'
    | '/settings-general'
    | '/settings-git-providers'
    | '/settings-integrations'
    | '/settings-jobs'
    | '/settings-llm-providers'
    | '/settings-notifications'
    | '/settings-operations'
    | '/settings-organization'
    | '/settings-privacy-redaction'
    | '/settings-provider-degradation'
    | '/settings-providers'
    | '/settings-rules-library'
    | '/settings-security'
    | '/settings-sso'
    | '/settings-team'
    | '/settings-token-usage'
    | '/settings-webhooks'
    | '/system-health'
    | '/dashboard/code-city'
    | '/reports/generate'
    | '/reports/viewer'
    | '/repositories/$repositoryId'
    | '/reviews/$reviewId'
    | '/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdoptionAnalyticsRoute: typeof AdoptionAnalyticsRoute
  HelpDiagnosticsRoute: typeof HelpDiagnosticsRoute
  IssuesRoute: typeof IssuesRoute
  LoginRoute: typeof LoginRoute
  MyWorkRoute: typeof MyWorkRoute
  OnboardingRoute: typeof OnboardingRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
  ReviewsRoute: typeof ReviewsRouteWithChildren
  ScanErrorRecoveryRoute: typeof ScanErrorRecoveryRoute
  ScanProgressRoute: typeof ScanProgressRoute
  SessionRecoveryRoute: typeof SessionRecoveryRoute
  SettingsRoute: typeof SettingsRoute
  SettingsAdoptionAnalyticsRoute: typeof SettingsAdoptionAnalyticsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsAuditLogsRoute: typeof SettingsAuditLogsRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsByokRoute: typeof SettingsByokRoute
  SettingsCodeReviewRoute: typeof SettingsCodeReviewRoute
  SettingsConcurrencyRoute: typeof SettingsConcurrencyRoute
  SettingsContractValidationRoute: typeof SettingsContractValidationRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsGitProvidersRoute: typeof SettingsGitProvidersRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsJobsRoute: typeof SettingsJobsRoute
  SettingsLlmProvidersRoute: typeof SettingsLlmProvidersRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsOperationsRoute: typeof SettingsOperationsRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsPrivacyRedactionRoute: typeof SettingsPrivacyRedactionRoute
  SettingsProviderDegradationRoute: typeof SettingsProviderDegradationRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsRulesLibraryRoute: typeof SettingsRulesLibraryRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSsoRoute: typeof SettingsSsoRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  SettingsTokenUsageRoute: typeof SettingsTokenUsageRoute
  SettingsWebhooksRoute: typeof SettingsWebhooksRoute
  SystemHealthRoute: typeof SystemHealthRoute
  DashboardCodeCityRoute: typeof DashboardCodeCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-health': {
      id: '/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-webhooks': {
      id: '/settings-webhooks'
      path: '/settings-webhooks'
      fullPath: '/settings-webhooks'
      preLoaderRoute: typeof SettingsWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-token-usage': {
      id: '/settings-token-usage'
      path: '/settings-token-usage'
      fullPath: '/settings-token-usage'
      preLoaderRoute: typeof SettingsTokenUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-team': {
      id: '/settings-team'
      path: '/settings-team'
      fullPath: '/settings-team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-sso': {
      id: '/settings-sso'
      path: '/settings-sso'
      fullPath: '/settings-sso'
      preLoaderRoute: typeof SettingsSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-security': {
      id: '/settings-security'
      path: '/settings-security'
      fullPath: '/settings-security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-rules-library': {
      id: '/settings-rules-library'
      path: '/settings-rules-library'
      fullPath: '/settings-rules-library'
      preLoaderRoute: typeof SettingsRulesLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-providers': {
      id: '/settings-providers'
      path: '/settings-providers'
      fullPath: '/settings-providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-provider-degradation': {
      id: '/settings-provider-degradation'
      path: '/settings-provider-degradation'
      fullPath: '/settings-provider-degradation'
      preLoaderRoute: typeof SettingsProviderDegradationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-privacy-redaction': {
      id: '/settings-privacy-redaction'
      path: '/settings-privacy-redaction'
      fullPath: '/settings-privacy-redaction'
      preLoaderRoute: typeof SettingsPrivacyRedactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-organization': {
      id: '/settings-organization'
      path: '/settings-organization'
      fullPath: '/settings-organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-operations': {
      id: '/settings-operations'
      path: '/settings-operations'
      fullPath: '/settings-operations'
      preLoaderRoute: typeof SettingsOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-notifications': {
      id: '/settings-notifications'
      path: '/settings-notifications'
      fullPath: '/settings-notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-llm-providers': {
      id: '/settings-llm-providers'
      path: '/settings-llm-providers'
      fullPath: '/settings-llm-providers'
      preLoaderRoute: typeof SettingsLlmProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-jobs': {
      id: '/settings-jobs'
      path: '/settings-jobs'
      fullPath: '/settings-jobs'
      preLoaderRoute: typeof SettingsJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-integrations': {
      id: '/settings-integrations'
      path: '/settings-integrations'
      fullPath: '/settings-integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-git-providers': {
      id: '/settings-git-providers'
      path: '/settings-git-providers'
      fullPath: '/settings-git-providers'
      preLoaderRoute: typeof SettingsGitProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-general': {
      id: '/settings-general'
      path: '/settings-general'
      fullPath: '/settings-general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-contract-validation': {
      id: '/settings-contract-validation'
      path: '/settings-contract-validation'
      fullPath: '/settings-contract-validation'
      preLoaderRoute: typeof SettingsContractValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-concurrency': {
      id: '/settings-concurrency'
      path: '/settings-concurrency'
      fullPath: '/settings-concurrency'
      preLoaderRoute: typeof SettingsConcurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-code-review': {
      id: '/settings-code-review'
      path: '/settings-code-review'
      fullPath: '/settings-code-review'
      preLoaderRoute: typeof SettingsCodeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-byok': {
      id: '/settings-byok'
      path: '/settings-byok'
      fullPath: '/settings-byok'
      preLoaderRoute: typeof SettingsByokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-billing': {
      id: '/settings-billing'
      path: '/settings-billing'
      fullPath: '/settings-billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-audit-logs': {
      id: '/settings-audit-logs'
      path: '/settings-audit-logs'
      fullPath: '/settings-audit-logs'
      preLoaderRoute: typeof SettingsAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-appearance': {
      id: '/settings-appearance'
      path: '/settings-appearance'
      fullPath: '/settings-appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-adoption-analytics': {
      id: '/settings-adoption-analytics'
      path: '/settings-adoption-analytics'
      fullPath: '/settings-adoption-analytics'
      preLoaderRoute: typeof SettingsAdoptionAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-recovery': {
      id: '/session-recovery'
      path: '/session-recovery'
      fullPath: '/session-recovery'
      preLoaderRoute: typeof SessionRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-progress': {
      id: '/scan-progress'
      path: '/scan-progress'
      fullPath: '/scan-progress'
      preLoaderRoute: typeof ScanProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-error-recovery': {
      id: '/scan-error-recovery'
      path: '/scan-error-recovery'
      fullPath: '/scan-error-recovery'
      preLoaderRoute: typeof ScanErrorRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-diagnostics': {
      id: '/help-diagnostics'
      path: '/help-diagnostics'
      fullPath: '/help-diagnostics'
      preLoaderRoute: typeof HelpDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adoption-analytics': {
      id: '/adoption-analytics'
      path: '/adoption-analytics'
      fullPath: '/adoption-analytics'
      preLoaderRoute: typeof AdoptionAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/reviews/$reviewId': {
      id: '/reviews/$reviewId'
      path: '/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewIdRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/repositories/$repositoryId': {
      id: '/repositories/$repositoryId'
      path: '/$repositoryId'
      fullPath: '/repositories/$repositoryId'
      preLoaderRoute: typeof RepositoriesRepositoryIdRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/reports/viewer': {
      id: '/reports/viewer'
      path: '/viewer'
      fullPath: '/reports/viewer'
      preLoaderRoute: typeof ReportsViewerRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/generate': {
      id: '/reports/generate'
      path: '/generate'
      fullPath: '/reports/generate'
      preLoaderRoute: typeof ReportsGenerateRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/dashboard/code-city': {
      id: '/dashboard/code-city'
      path: '/dashboard/code-city'
      fullPath: '/dashboard/code-city'
      preLoaderRoute: typeof DashboardCodeCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsGenerateRoute: typeof ReportsGenerateRoute
  ReportsViewerRoute: typeof ReportsViewerRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsGenerateRoute: ReportsGenerateRoute,
  ReportsViewerRoute: ReportsViewerRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface RepositoriesRouteChildren {
  RepositoriesRepositoryIdRoute: typeof RepositoriesRepositoryIdRoute
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesRepositoryIdRoute: RepositoriesRepositoryIdRoute,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

interface ReviewsRouteChildren {
  ReviewsReviewIdRoute: typeof ReviewsReviewIdRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsReviewIdRoute: ReviewsReviewIdRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdoptionAnalyticsRoute: AdoptionAnalyticsRoute,
  HelpDiagnosticsRoute: HelpDiagnosticsRoute,
  IssuesRoute: IssuesRoute,
  LoginRoute: LoginRoute,
  MyWorkRoute: MyWorkRoute,
  OnboardingRoute: OnboardingRoute,
  ReportsRoute: ReportsRouteWithChildren,
  RepositoriesRoute: RepositoriesRouteWithChildren,
  ReviewsRoute: ReviewsRouteWithChildren,
  ScanErrorRecoveryRoute: ScanErrorRecoveryRoute,
  ScanProgressRoute: ScanProgressRoute,
  SessionRecoveryRoute: SessionRecoveryRoute,
  SettingsRoute: SettingsRoute,
  SettingsAdoptionAnalyticsRoute: SettingsAdoptionAnalyticsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAuditLogsRoute: SettingsAuditLogsRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsByokRoute: SettingsByokRoute,
  SettingsCodeReviewRoute: SettingsCodeReviewRoute,
  SettingsConcurrencyRoute: SettingsConcurrencyRoute,
  SettingsContractValidationRoute: SettingsContractValidationRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsGitProvidersRoute: SettingsGitProvidersRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsJobsRoute: SettingsJobsRoute,
  SettingsLlmProvidersRoute: SettingsLlmProvidersRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsOperationsRoute: SettingsOperationsRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsPrivacyRedactionRoute: SettingsPrivacyRedactionRoute,
  SettingsProviderDegradationRoute: SettingsProviderDegradationRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsRulesLibraryRoute: SettingsRulesLibraryRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSsoRoute: SettingsSsoRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  SettingsTokenUsageRoute: SettingsTokenUsageRoute,
  SettingsWebhooksRoute: SettingsWebhooksRoute,
  SystemHealthRoute: SystemHealthRoute,
  DashboardCodeCityRoute: DashboardCodeCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
